-- ExcelsusDS external schema for Supabase Postgres.
-- Apply with `supabase db push` in a non-production project first.

create type public.app_role as enum ('user', 'admin');
create type public.candidate_stage as enum ('inbox', 'investigate', 'watch', 'source', 'ready_to_list', 'live', 'review', 'archive');
create type public.candidate_decision as enum ('launch', 'watch', 'kill');
create type public.evidence_kind as enum ('observed', 'assumption');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  role public.app_role not null default 'user',
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  trial_started_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table public.candidates (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  title varchar(255) not null,
  source_url text,
  source_label varchar(120) not null default 'Manual capture',
  category varchar(100),
  stage public.candidate_stage not null default 'inbox',
  decision public.candidate_decision,
  decision_note text,
  recheck_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index candidates_owner_updated_idx on public.candidates(owner_id, updated_at desc);

create table public.cost_profiles (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null unique references public.candidates(id) on delete cascade,
  source_currency varchar(3) not null default 'USD',
  selling_currency varchar(3) not null default 'USD',
  selling_price numeric(12,2) not null,
  product_cost numeric(12,2) not null,
  shipping_cost numeric(12,2) not null,
  fee_rate numeric(5,2) not null,
  return_rate numeric(5,2) not null,
  updated_at timestamptz not null default now()
);

create table public.evidence_snapshots (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null references public.candidates(id) on delete cascade,
  kind public.evidence_kind not null,
  label varchar(160) not null,
  value text not null,
  source_url text,
  note text,
  created_at timestamptz not null default now()
);
create index evidence_candidate_created_idx on public.evidence_snapshots(candidate_id, created_at desc);

create table public.pipeline_events (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null references public.candidates(id) on delete cascade,
  from_stage public.candidate_stage,
  to_stage public.candidate_stage not null,
  note text,
  created_at timestamptz not null default now()
);
create index pipeline_candidate_created_idx on public.pipeline_events(candidate_id, created_at desc);

create table public.listing_briefs (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null unique references public.candidates(id) on delete cascade,
  title varchar(255) not null,
  description text not null,
  item_specifics text,
  checklist text,
  updated_at timestamptz not null default now()
);

create table public.outcomes (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null unique references public.candidates(id) on delete cascade,
  units_sold integer not null default 0 check (units_sold >= 0),
  returns_count integer not null default 0 check (returns_count >= 0),
  revenue numeric(12,2) not null default 0.00,
  note text,
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger candidates_updated_at before update on public.candidates for each row execute function public.set_updated_at();
create trigger cost_profiles_updated_at before update on public.cost_profiles for each row execute function public.set_updated_at();
create trigger listing_briefs_updated_at before update on public.listing_briefs for each row execute function public.set_updated_at();
create trigger outcomes_updated_at before update on public.outcomes for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, email)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'), new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

-- Browser-facing tables: never grant anonymous access.
revoke all on public.profiles, public.candidates, public.cost_profiles, public.evidence_snapshots, public.pipeline_events, public.listing_briefs, public.outcomes from anon;
grant select on public.profiles to authenticated;
grant select, insert, update, delete on public.candidates, public.cost_profiles, public.evidence_snapshots, public.pipeline_events, public.listing_briefs, public.outcomes to authenticated;
grant usage, select on sequence public.candidates_id_seq, public.cost_profiles_id_seq, public.evidence_snapshots_id_seq, public.pipeline_events_id_seq, public.listing_briefs_id_seq, public.outcomes_id_seq to authenticated;

alter table public.profiles enable row level security;
alter table public.candidates enable row level security;
alter table public.cost_profiles enable row level security;
alter table public.evidence_snapshots enable row level security;
alter table public.pipeline_events enable row level security;
alter table public.listing_briefs enable row level security;
alter table public.outcomes enable row level security;

create policy profiles_read_self on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy candidates_owner_all on public.candidates for all to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy cost_profiles_owner_all on public.cost_profiles for all to authenticated using (exists (select 1 from public.candidates c where c.id = candidate_id and c.owner_id = (select auth.uid()))) with check (exists (select 1 from public.candidates c where c.id = candidate_id and c.owner_id = (select auth.uid())));
create policy evidence_owner_all on public.evidence_snapshots for all to authenticated using (exists (select 1 from public.candidates c where c.id = candidate_id and c.owner_id = (select auth.uid()))) with check (exists (select 1 from public.candidates c where c.id = candidate_id and c.owner_id = (select auth.uid())));
create policy pipeline_owner_all on public.pipeline_events for all to authenticated using (exists (select 1 from public.candidates c where c.id = candidate_id and c.owner_id = (select auth.uid()))) with check (exists (select 1 from public.candidates c where c.id = candidate_id and c.owner_id = (select auth.uid())));
create policy listing_owner_all on public.listing_briefs for all to authenticated using (exists (select 1 from public.candidates c where c.id = candidate_id and c.owner_id = (select auth.uid()))) with check (exists (select 1 from public.candidates c where c.id = candidate_id and c.owner_id = (select auth.uid())));
create policy outcomes_owner_all on public.outcomes for all to authenticated using (exists (select 1 from public.candidates c where c.id = candidate_id and c.owner_id = (select auth.uid()))) with check (exists (select 1 from public.candidates c where c.id = candidate_id and c.owner_id = (select auth.uid())));
